package pojo;
// Generated Apr 11, 2016 1:26:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Farm generated by hbm2java
 */
public class Farm  implements java.io.Serializable {


     private int farmId;
     private String farmName;
     private String farmLocation;
     private Date startDate;
     private Set ships = new HashSet(0);

    public Farm() {
    }

	
    public Farm(int farmId) {
        this.farmId = farmId;
    }
    public Farm(int farmId, String farmName, String farmLocation, Date startDate, Set ships) {
       this.farmId = farmId;
       this.farmName = farmName;
       this.farmLocation = farmLocation;
       this.startDate = startDate;
       this.ships = ships;
    }
   
    public int getFarmId() {
        return this.farmId;
    }
    
    public void setFarmId(int farmId) {
        this.farmId = farmId;
    }
    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }
    public String getFarmLocation() {
        return this.farmLocation;
    }
    
    public void setFarmLocation(String farmLocation) {
        this.farmLocation = farmLocation;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Set getShips() {
        return this.ships;
    }
    
    public void setShips(Set ships) {
        this.ships = ships;
    }




}


