package pojo;
// Generated Apr 21, 2016 7:11:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private Integer sensorId;
     private Reader reader;
     private SensorType sensorType;
     private Set sensorDatas = new HashSet(0);

    public Sensor() {
    }

    public Sensor(Reader reader, SensorType sensorType, Set sensorDatas) {
       this.reader = reader;
       this.sensorType = sensorType;
       this.sensorDatas = sensorDatas;
    }
   
    public Integer getSensorId() {
        return this.sensorId;
    }
    
    public void setSensorId(Integer sensorId) {
        this.sensorId = sensorId;
    }
    public Reader getReader() {
        return this.reader;
    }
    
    public void setReader(Reader reader) {
        this.reader = reader;
    }
    public SensorType getSensorType() {
        return this.sensorType;
    }
    
    public void setSensorType(SensorType sensorType) {
        this.sensorType = sensorType;
    }
    public Set getSensorDatas() {
        return this.sensorDatas;
    }
    
    public void setSensorDatas(Set sensorDatas) {
        this.sensorDatas = sensorDatas;
    }




}


