package pojo;
// Generated Apr 21, 2016 7:11:11 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SensorData generated by hbm2java
 */
public class SensorData implements java.io.Serializable {

    private Integer sensorDataId;
    private Date timestamp;
    private Sensor sensor;
    private Integer value;

    public SensorData() {
    }

    public SensorData(Sensor sensor, Integer value) {
        this.sensor = sensor;
        this.value = value;
    }

    public Integer getSensorDataId() {
        return this.sensorDataId;
    }

    public void setSensorDataId(Integer sensorDataId) {
        this.sensorDataId = sensorDataId;
    }

    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public Sensor getSensor() {
        return this.sensor;
    }

    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }

    public Integer getValue() {
        return this.value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

}
