package pojo;
// Generated Apr 11, 2016 1:26:09 PM by Hibernate Tools 4.3.1



/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private int sensorId;
     private Reader reader;
     private SensorType sensorType;

    public Sensor() {
    }

	
    public Sensor(int sensorId) {
        this.sensorId = sensorId;
    }
    public Sensor(int sensorId, Reader reader, SensorType sensorType) {
       this.sensorId = sensorId;
       this.reader = reader;
       this.sensorType = sensorType;
    }
   
    public int getSensorId() {
        return this.sensorId;
    }
    
    public void setSensorId(int sensorId) {
        this.sensorId = sensorId;
    }
    public Reader getReader() {
        return this.reader;
    }
    
    public void setReader(Reader reader) {
        this.reader = reader;
    }
    public SensorType getSensorType() {
        return this.sensorType;
    }
    
    public void setSensorType(SensorType sensorType) {
        this.sensorType = sensorType;
    }




}


