package pojo;
// Generated Apr 21, 2016 7:11:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SensorType generated by hbm2java
 */
public class SensorType implements java.io.Serializable {

    private Integer sensorTypeId;
    private String type;
    private String description;
    private Set sensors = new HashSet(0);

    public SensorType() {
    }

    public SensorType(String type, String description, Set sensors) {
        this.type = type;
        this.description = description;
        this.sensors = sensors;
    }

    public Integer getSensorTypeId() {
        return this.sensorTypeId;
    }

    public void setSensorTypeId(Integer sensorTypeId) {
        this.sensorTypeId = sensorTypeId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSensors() {
        return this.sensors;
    }

    public void setSensors(Set sensors) {
        this.sensors = sensors;
    }

}
