package pojo;
// Generated Apr 11, 2016 1:26:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ship generated by hbm2java
 */
public class Ship  implements java.io.Serializable {


     private int shipId;
     private Farm farm;
     private String shipName;
     private Date startDate;
     private Set lines = new HashSet(0);

    public Ship() {
    }

	
    public Ship(int shipId) {
        this.shipId = shipId;
    }
    public Ship(int shipId, Farm farm, String shipName, Date startDate, Set lines) {
       this.shipId = shipId;
       this.farm = farm;
       this.shipName = shipName;
       this.startDate = startDate;
       this.lines = lines;
    }
   
    public int getShipId() {
        return this.shipId;
    }
    
    public void setShipId(int shipId) {
        this.shipId = shipId;
    }
    public Farm getFarm() {
        return this.farm;
    }
    
    public void setFarm(Farm farm) {
        this.farm = farm;
    }
    public String getShipName() {
        return this.shipName;
    }
    
    public void setShipName(String shipName) {
        this.shipName = shipName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Set getLines() {
        return this.lines;
    }
    
    public void setLines(Set lines) {
        this.lines = lines;
    }




}


